name: Publish on push to main.

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: source

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up Dotnet.
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore "./TylerDM.StandardLibrary.Reflection"

      - name: Build project
        run: dotnet build "./TylerDM.StandardLibrary.Reflection" --configuration Release --no-restore

      - name: Pack project
        run: dotnet pack "./TylerDM.StandardLibrary.Reflection" --configuration Release --no-build --output ./nupkg 

      - name: Publish to NuGet
        run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
